name: Build XojoScript Bytecode Compiler and VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64, x86, arm64, armv7]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # ------------------------------
      # Linux (Ubuntu) using apt-get
      # ------------------------------
      - name: Build on Linux (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          echo "Building for architecture ${{ matrix.arch }} on Linux (Ubuntu)"
          sudo apt-get update
          sudo apt-get install -y libffi-dev
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            g++ -std=c++17 -o xojoscript xojoscript.cpp -lffi
          elif [ "${{ matrix.arch }}" = "x86" ]; then
            sudo apt-get install -y g++-multilib
            g++ -std=c++17 -m32 -o xojoscript xojoscript.cpp -lffi
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            sudo apt-get update
            sudo apt-get install -y aarch64-linux-gnu-g++
            aarch64-linux-gnu-g++ -std=c++17 -o xojoscript xojoscript.cpp -lffi
          elif [ "${{ matrix.arch }}" = "armv7" ]; then
            sudo apt-get update
            sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
            arm-linux-gnueabihf-g++ -std=c++17 -o xojoscript xojoscript.cpp -lffi
          fi

      # ------------------------------
      # macOS using pacman (via Homebrew)
      # ------------------------------
      - name: Build on macOS using pacman
        if: runner.os == 'macos-latest'
        run: |
          echo "Building for architecture ${{ matrix.arch }} on macOS using pacman"
          echo "Installing pacman via Homebrew (if not already installed)"
          brew install pacman || echo "Pacman already installed"
          # Use pacman to install libffi – note that pacman on macOS is not typical and may require manual configuration.
          sudo pacman -S --noconfirm libffi
          if [ "${{ matrix.arch }}" = "x86_64" ] || [ "${{ matrix.arch }}" = "arm64" ]; then
            clang++ -std=c++17 -arch ${{ matrix.arch }} -o xojoscript xojoscript.cpp -lffi
          else
            echo "Skipping unsupported architecture ${{ matrix.arch }} on macOS"
          fi

      # ------------------------------
      # Windows using MSYS2 with pacman
      # ------------------------------
      - name: Setup MSYS2 on Windows
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          # Use pacman to install libffi. In MSYS2 the package name is often "mingw-w64-x86_64-libffi",
          # but here we follow the requested command.
          install: libffi
          msystem: MINGW64

      - name: Build on Windows using pacman
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          echo "Building for architecture ${{ matrix.arch }} on Windows"
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            g++ -std=c++17 -o xojoscript.exe xojoscript.cpp -lffi
          elif [ "${{ matrix.arch }}" = "x86" ]; then
            g++ -std=c++17 -m32 -o xojoscript.exe xojoscript.cpp -lffi
          else
            echo "Cross-compiling for ${{ matrix.arch }} is not supported on Windows"
          fi